version: '3'
services:
  app:
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
      CRYPT_SALT: ${CRYPT_SALT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./src:/usr/app/src
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always

  postgres:
    ports:
      - ${DB_PORT}:${DB_PORT}
    build:
      context: ./src/db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
